export const GET_USER_NAME = 'GET_USER_NAME'
export const GET_TREE_NAME = 'GET_TREE_NAME'
export const GET_TREE_START = 'GET_TREE_START'
export const GET_INFO_TREE = 'GET_INFO-TREE'
export const ADD_AGE = 'ADD_AGE'
export const HARVEST_MANGO = 'HARVEST_MANGO'
export const DEAD_TREE = 'DEAD_TREE'
export const BACK_TO_HOME = 'BACK_TO_HOME'